[package]
name = "Yuich"
version = "0.1.0"
authors = ["marior765 <d.bohatyrchuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.1"
